// Generated by packages/theme/build.mjs from tokens.json. Do not edit.

import SwiftUI

enum Tokens {
    static let radius: CGFloat = 6

    static let background = ThemeColor(light: 0xf1f2f3, dark: 0x121414)
    static let foreground = ThemeColor(light: 0x434b52, dark: 0xf1f1f1)
    static let card = ThemeColor(light: 0xffffff, dark: 0x1a1c1e)
    static let cardForeground = ThemeColor(light: 0x434b52, dark: 0xf1f1f1)
    static let popover = ThemeColor(light: 0xffffff, dark: 0x232429)
    static let popoverForeground = ThemeColor(light: 0x434b52, dark: 0xf1f1f1)
    static let primary = ThemeColor(light: 0x4f96f2, dark: 0x5ea2f5)
    static let primaryForeground = ThemeColor(light: 0xffffff, dark: 0xffffff)
    static let secondary = ThemeColor(light: 0xf3f3f3, dark: 0x191919)
    static let secondaryForeground = ThemeColor(light: 0x717171, dark: 0xbbbbbb)
    static let muted = ThemeColor(light: 0xf3f3f3, dark: 0x191919)
    static let mutedForeground = ThemeColor(light: 0xa0a0a0, dark: 0x8a8a8a)
    static let accent = ThemeColor(light: 0xf6f7f8, dark: 0x2b2d2e)
    static let accentForeground = ThemeColor(light: 0x434b52, dark: 0xf1f1f1)
    static let destructive = ThemeColor(light: 0xdd5050, dark: 0xe06060)
    static let border = ThemeColor(light: 0xebecee, dark: 0x2a2c2f)
    static let input = ThemeColor(light: 0xe1e3e6, dark: 0x2a2c2f)
    static let ring = ThemeColor(light: 0x4f96f2, dark: 0x5ea2f5)
    static let star = ThemeColor(light: 0xf9775d, dark: 0xf9775d)
    static let chart1 = ThemeColor(light: 0xdd5050, dark: 0xdd5050)
    static let chart2 = ThemeColor(light: 0x24c2c2, dark: 0x24c2c2)
    static let chart3 = ThemeColor(light: 0xffa702, dark: 0xffa702)
    static let chart4 = ThemeColor(light: 0x539565, dark: 0x5fa872)
    static let chart5 = ThemeColor(light: 0x8074b1, dark: 0x8c80c0)
    static let sidebar = ThemeColor(light: 0xffffff, dark: 0x1a1c1e)
    static let sidebarForeground = ThemeColor(light: 0x434b52, dark: 0xc7c7c7)
    static let sidebarPrimary = ThemeColor(light: 0x4f96f2, dark: 0x5ea2f5)
    static let sidebarPrimaryForeground = ThemeColor(light: 0xffffff, dark: 0xffffff)
    static let sidebarAccent = ThemeColor(light: 0xf1f2f3, dark: 0x2b2d2e)
    static let sidebarAccentForeground = ThemeColor(light: 0x434b52, dark: 0xf1f1f1)
    static let sidebarBorder = ThemeColor(light: 0xebecee, dark: 0x2a2c2f)
    static let sidebarRing = ThemeColor(light: 0x4f96f2, dark: 0x5ea2f5)
    static let overlay = ThemeColor(light: 0x000000, dark: 0x000000)
}
