// Generates tokens.css and the Apple kit's Tokens.swift from tokens.json.
//
//   node packages/theme/build.mjs           writes both
//   node packages/theme/build.mjs --check   fails if either is out of date
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "../..");
const tokens = JSON.parse(readFileSync(join(here, "tokens.json"), "utf8"));
const names = Object.keys(tokens.light);

const missing = names.filter((name) => !(name in tokens.dark));
if (missing.length) throw new Error(`dark is missing ${missing.join(", ")}`);

const block = (selector, colors) =>
  `${selector} {\n${names.map((name) => `  --${name}: ${colors[name]};`).join("\n")}\n}`;

const css = `/* Generated by build.mjs from tokens.json. Do not edit. */

:root {
  --radius: ${tokens.radius}px;
}

${block(":root", tokens.light)}

${block("@media (prefers-color-scheme: dark) {\n  :root", tokens.dark).replace(/\n/g, "\n  ").replace(/\n  $/, "")}
}
`;

const camel = (name) => name.replace(/-(\w)/g, (_, letter) => letter.toUpperCase());
const hex = (color) => `0x${color.slice(1)}`;
const isNumber = (name) => typeof tokens.light[name] === "number";
const line = (name) =>
  isNumber(name)
    ? `    static let ${camel(name)} = ThemeNumber(light: ${tokens.light[name]}, dark: ${tokens.dark[name]})`
    : `    static let ${camel(name)} = ThemeColor(light: ${hex(tokens.light[name])}, dark: ${hex(tokens.dark[name])})`;
const swift = `// Generated by packages/theme/build.mjs from tokens.json. Do not edit.

import SwiftUI

enum Tokens {
    static let radius: CGFloat = ${tokens.radius}

${names.map(line).join("\n")}
}
`;

const outputs = [
  [join(here, "tokens.css"), css],
  [join(root, "packages/apple/Sources/MailUI/Shared/Theme/Tokens.swift"), swift],
];

if (process.argv.includes("--check")) {
  const stale = outputs.filter(([path, text]) => {
    try {
      return readFileSync(path, "utf8") !== text;
    } catch {
      return true;
    }
  });
  if (stale.length) {
    console.error(`Out of date: ${stale.map(([path]) => path.replace(root + "/", "")).join(", ")}. Run node packages/theme/build.mjs`);
    process.exit(1);
  }
  console.log("✓ Generated tokens are up to date");
} else {
  for (const [path, text] of outputs) writeFileSync(path, text);
  console.log("✓ Wrote tokens.css and Tokens.swift");
}
